language: node_js
node_js:
- '7.8'
services: mongodb
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
